const companyActions = {
  COMPANY_CREATE: 'COMPANY_CREATE',
  COMPANY_CREATE_SUCCESS: 'COMPANY_CREATE_SUCCESS',
  COMPANY_CREATE_ERROR: 'COMPANY_CREATE_ERROR',
  START_GET_COMPANY: 'START_GET_COMPANY',
  GET_COMPANY_SUCCESS: 'GET_COMPANY_SUCCESS',
  GET_COMPANY_ERROR: 'GET_COMPANY_ERROR',
};
export default companyActions;
