const postActions = {
  FETCH_POST: 'FETCH_POST',
  FETCH_POST_SUCCESS: 'FETCH_POST_SUCCESS',
  FETCH_POST_ERROR: 'FETCH_POST_ERROR',
  FETCH_POST_BY_USER: 'FETCH_POST_BY_USER',
  FETCH_POST_BY_USER_SUCCESS: 'FETCH_POST_BY_USER_SUCCESS',
  FETCH_POST_BY_USER_ERROR: 'FETCH_POST_BY_USER_ERROR',
};

export default postActions;
